name: Playwright CI

on:
  push:
    branches: [master]

jobs:
  test:
    name: Run tests with storageState
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: â¬‡ï¸ Download storageState.json
        uses: actions/download-artifact@v3
        with:
          name: storage
          path: .

      - name: ğŸŸ¦ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸ§ª Install Chromium only
        run: npx playwright install chromium

      - name: â–¶ï¸ Run Playwright tests
        run: npx playwright test
