name: UI Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  ui-tests:
    name: Run UI tests
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸŸ¦ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸ§ª Install Chromium only
        run: npx playwright install chromium

      - name: â–¶ï¸ Run UI tests (with Allure)
        run: npx playwright test src/ui/tests --reporter=line,allure-playwright
        env:
          BASE_UI_URL: https://www.discogs.com/
          BASE_URL: https://api.discogs.com/
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          LABEL_ID: '681346'

      - name: ğŸ“Š Generate Allure report
        run: npx allure generate --clean ./allure-results

      - name: ğŸ“¤ Upload Allure report artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: allure-report
          path: allure-report
