name: Upload storageState

on:
  workflow_dispatch: # Ğ²Ñ€ÑƒÑ‡Ğ½Ğ¾Ğ¹ Ğ·Ğ°Ğ¿ÑƒÑĞº Ğ¸Ğ· GitHub UI

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ğŸ“¤ Upload storageState.json
        uses: actions/upload-artifact@v4
        with:
          name: storage
          path: state.json
